### PR TITLE
add how to contribute step by step.

### PR DESCRIPTION
**Pull request by mikearino**
Added step by step instructions for contributing.

### CODE REVIEW

**Comment by benjaminwood** [comment]
@mikearino is this ready for review? If so, can you mark it ready for review?

**Comment by benjaminwood** [comment]
Yeah, agreed. Let's start from the very beginning!

**Comment by benjaminwood** [comment]
Hmmm, I guess the readme already mentions forking the code:

https://github.com/OfficeMomsandDads/scheduler/blob/50b4562d86fb12c27d11badb62210dd941b49840/README.md#L124

Maybe still worth mentioning in the step-by-step.

**Comment by mikearino** [comment]
@benjaminwood you bet!

**Pull request merged**
