### PR TITLE
Shifts

### PR DESCRIPTION
**Pull request by kyleboe**
- [x] allow schedulers to add new shifts

Adds shift related styling and UI/UX

Ref: #18 and #19

### CODE REVIEW

**Comment by benjaminwood** [comment]
Is preferred culture supposed to be part of the need request? As I recall that was bordering on too much identifying information about the kids. I could be forgetful, my head hasn't been in this for a week and a half :-)

**Comment by nvick** [comment]
Yes, we asked Sarah on our call about if she wanted it on the need request.

**Comment by benjaminwood** [comment]
Cool :blush:

**Comment by kyleboe** [comment]
Re-deployed to heroku

**Comment by benjaminwood** [comment]
:tada:

**Pull request merged**
