### PR TITLE
Bugfix: admin users ordered by full name

### PR DESCRIPTION
**Pull request by FatherofDharma**
#170

### CODE REVIEW

**Comment by dinjas** [comment]
This is difficult to test without a better understanding of how administrate works under the hood.

With normal controller actions, typically an instance variable is assigned to store the contents of what's being returned/rendered - in this case, administrate is using a slightly different approach and there doesn't seem to be a variable available to check. 

It's also doing some special handling with the view contents (eg. `response.body` is returning an empty string).

I agree that tests should be written, but it's not obvious to me how to do so.

One thing of note - there are some existing controller specs for admin pages (ie. `reports_controller_spec`) that are incorrect (sadly, I wrote that one). The controller specs need to be sure to sign in an admin user before testing behavior or the test will get redirected before the controller code ever runs.

**Comment by dinjas** [comment]
We did add specs, but they don't test the changes that were made in this PR, they are basically just smoke tests. 😄

**Comment by benjaminwood** [comment]
Yeah, really the only change was ordered. We could assert position of users in the response.body, but I'm not that concerned about that. It's most important that the code is executed since it depends on internal code from administrate.

**Comment by dinjas** [comment]
Yea, that's the weird thing... `respond.body` was `''` when we were attempting to add the specs. Now that I think about it, maybe that was indicative of something else.

**Comment by benjaminwood** [comment]
Controller specs don't render views by default. I generally prefer request specs, partially for this reason, but again, I was mainly concerned that the code was executed. :smile:

**Comment by dinjas** [comment]
Oh interesting haha. The main app I work on does render controller views - must be configured as such. Good to know!

**Pull request merged**
